name: Run main.py hourly (8:00~22:00 JST)

on:
  workflow_dispatch:         # 手動実行
  schedule:
    # ↓ JST 08:00（UTC 23:00）
    - cron: '0 23 * * *'
    # ↓ JST 09:35（混雑対策で35分にずらし）
    - cron: '35 0 * * *'
    # ↓ JST 10:40（混雑対策で40分にずらし）
    - cron: '40 1 * * *'
    # ↓ JST 11:45（混雑対策で45分にずらし）
    - cron: '45 2 * * *'
    # ↓ JST 12:00
    - cron: '0 3 * * *'
    # ↓ JST 13:00
    - cron: '0 4 * * *'
    # ↓ JST 14:00
    - cron: '0 5 * * *'
    # ↓ JST 15:00
    - cron: '0 6 * * *'
    # ↓ JST 16:00
    - cron: '0 7 * * *'
    # ↓ JST 17:00
    - cron: '0 8 * * *'
    # ↓ JST 18:00
    - cron: '0 9 * * *'
    # ↓ JST 19:00
    - cron: '0 10 * * *'
    # ↓ JST 20:00
    - cron: '0 11 * * *'
    # ↓ JST 21:00
    - cron: '0 12 * * *'
    # ↓ JST 22:00
    - cron: '0 13 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python main.py
